apiVersion: apps/v1
kind: Deployment
metadata:
  name: do-some-sql-app-deployment
  labels:
    app.kubernetes.io/name: do-some-sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: do-some-sql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: do-some-sql
      annotations:  
        dapr.io/app-id: do-some-sql-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
    spec:
      containers:
      - name: java-app
        image: docker.io/salaboy/do-some-sql:testcontainers-1
        env: 
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://${DB_ENDPOINT}:${DB_PORT}/postgres
          - name: SPRING_DATASOURCE_USERNAME
            value: postgres          
          - name: DB_ENDPOINT
            value: postgresql.default.svc.cluster.local
          - name: DB_PORT
            value: "5432"
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgres-password
        ports: 
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: do-some-sql-service
spec:
  selector:
    app.kubernetes.io/name: do-some-sql-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080